# Generated by Django 2.2.10 on 2021-11-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_request',
        ),
    ]
